function diffused = diffuse(mat)
            % Given a matrix containing a fluid intensity (0 to 1),
            % diffuse the fluid across the matrix evenly.
            [m, n] = size(mat);
            
            up = [2:m 1];
            down = [m 1:m-1];
            left = [2:n 1];
            right = [n 1:n-1];
            
            diffused = 1/48 * mat(up, left) + ...
                       1/48 *mat(up, :) + ...
                       1/48 *mat(up, right) + ...
                       1/48 *mat(:, left) + ...
                       5/6*mat(:, :) + ...
                       1/48 *mat(:, right) + ...
                       1/48 *mat(down, left) + ...
                       1/48 *mat(down, :) + ...
                       1/48 *mat(down, right);
        end