function diffused = diffuse_aim(mat)
            % Given a matrix containing a fluid intensity (0 to 1),
            % diffuse the fluid across the matrix evenly.%% 
            [m, n] = size(mat);
            
            up = [2:m 1];
            down = [m 1:m-1];
            left = [2:n 1];
            right = [n 1:n-1];
            
            diffused = 1/46 * mat(up, left) + ...
                       1/46 *mat(up, :) + ...
                       1/46 *mat(up, right) + ...
                       1/46 *mat(:, left) + ...
                       19/23*mat(:, :) + ...
                       1/46 *mat(:, right) + ...
                       1/46 *mat(down, left) + ...
                       1/46 *mat(down, :) + ...
                       1/46 *mat(down, right);
        end